name: Java CI with Gradle

on:  
  push:    
    branches: [ "master" ]  
  pull_request:    
    branches: [ "master" ]

jobs:  
  build:    
    runs-on: ubuntu-latest    
    permissions:      
      contents: read    
    steps:    
    - uses: actions/checkout@v4    
    - name: Set up JDK 17      
      uses: actions/setup-java@v4      
      with:        
        java-version: '17'        
        distribution: 'temurin'    
    - name: Setup Gradle      
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582      
      with:
        gradle-version: '8.0'  
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew 
    - name: Build with Gradle Wrapper      
      run: ./gradlew build  
    
    - name: Install OWASP Dependency-Check
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.2.1/dependency-check-7.2.1-release.zip
        unzip dependency-check-7.2.1-release.zip
        mv dependency-check /opt/dependency-check
    
    - name: Create report output directory
      run: mkdir -p dependency-check-report
    
    - name: Run OWASP Dependency-Check
      run: |
        /opt/dependency-check/bin/dependency-check.sh --project "osd-records-mgt-web-appl" --scan ./ --format "ALL" --out dependency-check-report

    - name: Upload OWASP Dependency-Check report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: dependency-check-report

  dependency-submission:    
    runs-on: ubuntu-latest    
    permissions:      
      contents: write    
    steps:    
    - uses: actions/checkout@v4    
    - name: Set up JDK 17      
      uses: actions/setup-java@v4      
      with:        
        java-version: '17'        
        distribution: 'temurin'    
    - name: Generate and submit dependency graph      
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582

  performance-test:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install JMeter
      run: sudo apt-get install -y jmeter

    - name: Run JMeter performance tests
      run: |
        mkdir -p jmeter-reports
        jmeter -n -t jmeter-tests/testplan.jmx -l jmeter-reports/results.jtl -e -o jmeter-reports/

    - name: Upload JMeter Results
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-results
        path: jmeter-reports