name: Java CI with Gradle

on:  
  push:    
    branches: [ "master" ]  
  pull_request:    
    branches: [ "master" ]

jobs:  
  build:    
    runs-on: ubuntu-latest    
    permissions:      
      contents: read    
    steps:    
    - uses: actions/checkout@v8 
    - name: Set up JDK 17      
      uses: actions/setup-java@v8 
      with:        
        java-version: '17'        
        distribution: 'temurin'    
    - name: Setup Gradle      
      uses: gradle/actions/setup-gradle@v8  
      with:
        gradle-version: '8.0'
    - name: Build with Gradle Wrapper      
      run: ./gradlew build  

  dependency-submission:    
    runs-on: ubuntu-latest    
    permissions:      
      contents: write    
    steps:    
    - uses: actions/checkout@v8 
    - name: Set up JDK 17      
      uses: actions/setup-java@v8
      with:        
        java-version: '17'        
        distribution: 'temurin'    
    - name: Generate and submit dependency graph      
      uses: gradle/actions/dependency-submission@v8
